search:
    method: fdarts 
    search_space: nas-bench-201
    nodes: 3
    exclude_zero: true
    arch_grad_clip: null 
    arch_learning_rate: 0.0003
    arch_weight_decay: 0.001
    discrete: false
    adapt_lr: false 
    gd: true
    trace_norm: null
    unrolled: false 

train:
    layers: 5
