search:
    method: darts
    search_space: pcdarts
    nodes: 4
    exclude_zero: false
    train_portion: 0.5
    arch_learning_rate: 0.0006
    arch_weight_decay: 0.001
    unrolled: false 
    discrete: false
