search:
    method: darts
    search_space: darts
    nodes: 4
    exclude_zero: false
    train_portion: 0.5
    arch_learning_rate: 0.0003
    arch_weight_decay: 0.001
    unrolled: false
    discrete: false
