search:
    method: gdarts 
    search_space: nas-bench-201
    nodes: 3
    exclude_zero: false
    arch_grad_clip: null 
    arch_learning_rate: 0.0003
    arch_weight_decay: 0.001
    edge_learning_rate: 0.0
    discrete: false
    adapt_lr: false 
    gd: true
    learn_edges: false
    trace_norm: null

train:
    layers: 5
