search:
    method: egdas
    search_space: darts_small
    nodes: 4
    arch_grad_clip: null
    train_portion: 0.5
    arch_learning_rate: 0.01
    max_tau: 10
    min_tau: 0.1
    discrete: true
    warmup_epochs: 50
    arch_weight_decay: 0.01

train:
    layers: 5

